import { ReactNode } from 'react';
import { Metadata } from 'next';
import dynamic from 'next/dynamic';
import './css/bootstrap.min.css';
import './css/main.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
